name: sample1
description: "A new Flutter project."

# The following line prevents accidental publishing to pub.dev.
# Remove this line if you want to publish your package.
publish_to: 'none'

# The version and build number for your application.
# Format: [major].[minor].[patch] followed by an optional build number.
# Example: 1.0.0+1 (version 1.0.0, build 1)
version: 1.0.0+1

# The Dart SDK version required to run this project.
# The caret (^) means compatibility with future minor versions.
environment:
  sdk: ">=3.7.0 <4.0.0"

# Dependencies required for the app to function.
dependencies:
  flutter:
    sdk: flutter  # This ensures the project uses the Flutter SDK.

  # Plugin for scanning QR codes.
  qr_code_scanner: ^1.0.1

  # Provides Cupertino-style icons for iOS-like design.
  cupertino_icons: ^1.0.8
  mobile_scanner: ^6.0.7
  http: ^1.3.0

# Dependencies only needed for development and testing.
dev_dependencies:
  flutter_test:
    sdk: flutter  # Required for writing and running Flutter tests.

  # Recommended linting rules for best coding practices.
  flutter_lints: ^5.0.0

# Flutter-specific configurations.
flutter:
  # Enables the use of Material Design icons in the app.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
